### ISSUE TITLE
Missing wiring diagram?

### ISSUE THREAD

**Issue by Swekkerooni** [tTargiel/nRF24L01-eavesdropping#1]
Hi Tomasz,

I was trying to build your project, but it appears that the wiring diagram is missing from the documentation, contrary to what is written on the project page. Could you let me know where to find it?

I am trying to use a Pi Zero W (not 2nd gen 2W) by the way - it appears I managed to install everything correctly and were able to load the webpage and all. If anyone could confirm this should work, that would be nice.

But now all I just need to hook up an NRF24 module to verify this.

**Comment by tTargiel** [comment]
Hi, the wiring diagram is available at documentation page of py-nrf24: https://github.com/bjarne-hansen/py-nrf24

This project should work fine under Raspberry Pi Zero W - the one that you are using. Keep in mind that although this vulnerability may affect a number of Microsoft wireless keyboards, my code was tested only against Microsoft Wireless Keyboard 800 that was available to me.

Disclaimer: This project is for educational and research purposes only. Any misuse of this project for illegal activities is strictly prohibited. Use responsibly and respect privacy and data protection laws.

**Comment by Swekkerooni** [comment]
Awesome, I didn't make the link to that external documentation. I kept going through the files and everything on this particular github page.

Thank you for your quick reply! - Understood on the disclaimer, but I think my IT dept. has one of those K800s in an e-waste bin somewhere and that together with this project would make a great talking point for cyber security awareness. Just another tool in the toolbox to talk about, alongside deauthers, BadUSB and Flipper Zero NRF injection
